version: "3.8"

services:
  app:
    container_name: shop-ui
    image: shop-ui
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3006:3006
    stdin_open: true
    command: yarn start
